name: simple_async_builder
description: Async widget builders made simple
version: 0.0.1
homepage: https://github.com/bartektartanus/simple_async_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  either_dart: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
