name: simple_async_builder
description: Async widget builders made simple. Easy to use `Future` and `Stream` builders.
version: 0.1.0
homepage: https://github.com/bartektartanus/simple_async_builder

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  either_dart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
